services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
      - ./static:/static
    command: uv run python manage.py runserver 0.0.0.0:8000
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DEBUG=1
