version: "3.9"

services:
  web:
    build:
      context: .
      target: prod
    container_name: learning-platform-web
    command: >
      gunicorn learningPlatform.asgi:application
      -w 3
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      - learning-net

  celery:
    build:
      context: .
      target: prod
    container_name: learning-platform-celery
    command: celery -A learningPlatform worker --loglevel=info
    env_file:
      - .env
    networks:
      - learning-net

networks:
  learning-net:
    driver: bridge
