# Generated by Django 5.2.6 on 2025-09-25 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_learning_score', models.PositiveIntegerField(default=0)),
                ('hands_on_learning_score', models.PositiveIntegerField(default=0)),
                ('reading_learning_score', models.PositiveIntegerField(default=0)),
                ('chosen_subject', models.CharField(choices=[('programming', 'Programming and software development'), ('music', 'Musical theory and composition'), ('art', 'Art history and art crafting')], max_length=50)),
                ('assessment_score', models.PositiveIntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=13)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('registration_step', models.IntegerField(default=1)),
                ('registration_completed', models.BooleanField(default=False)),
                ('learning_pace', models.FloatField(default=0.0, help_text='Lessons completed per week')),
                ('pace_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
