# Generated by Django 5.2.6 on 2025-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('programming', 'Programming and software development'), ('music', 'Musical theory and composition'), ('art', 'Art history and art crafting')], help_text="topic's subject", max_length=50)),
                ('question_text', models.TextField(help_text='The question users will answer')),
                ('answers', models.JSONField(help_text='options answers')),
                ('correct_answer', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')])),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=40)),
                ('points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='learningprofile',
            old_name='assessment_completed',
            new_name='difficulty_assessment_completed',
        ),
        migrations.RenameField(
            model_name='learningprofile',
            old_name='assessment_date',
            new_name='difficulty_assessment_date',
        ),
        migrations.AlterField(
            model_name='learningprofile',
            name='assessment_score',
            field=models.PositiveIntegerField(default=0, help_text='from 0 to 100'),
        ),
    ]
