# Generated by Django 5.2.6 on 2025-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_difficultyquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultyquestions',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
