# Generated by Django 5.2.6 on 2025-10-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_difficultyquestions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficultyquestions',
            name='status',
        ),
    ]
