# Generated by Django 5.2.6 on 2025-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_difficultyquestions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprofile',
            name='difficulty_assessment_ready',
            field=models.BooleanField(default=False),
        ),
    ]
