# Generated by Django 5.2.6 on 2025-10-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_learningprofile_difficulty_assessment_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningprofile',
            name='hands_on_learning_score',
        ),
        migrations.RemoveField(
            model_name='learningprofile',
            name='reading_learning_score',
        ),
        migrations.RemoveField(
            model_name='learningprofile',
            name='visual_learning_score',
        ),
    ]
