# Generated by Django 5.2.6 on 2025-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_content',
            field=models.JSONField(help_text='AI-generated lesson content based on skills'),
        ),
    ]
