# Generated by Django 5.2.6 on 2025-10-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_completed',
            field=models.BooleanField(default=False),
        ),
    ]
