# Generated by Django 5.2.6 on 2025-10-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_lesson_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_completed',
        ),
    ]
