# Generated by Django 5.2.6 on 2025-10-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lesson_lesson_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='error_message',
            field=models.TextField(default='no error'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(default='ready', max_length=50),
            preserve_default=False,
        ),
    ]
