# Generated by Django 5.2.6 on 2025-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_topic_error_message_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(default='not ready', max_length=50),
        ),
    ]
