# Generated by Django 5.2.6 on 2025-10-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_topic_error_message_alter_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
