# Generated by Django 5.2.6 on 2025-10-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_topic_error_message_alter_topic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100),
        ),
    ]
