# Generated by Django 5.2.6 on 2025-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_topic_error_message_remove_topic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(choices=[('programming', 'Programming and software development'), ('music', 'Musical theory and composition'), ('art', 'Art history and art crafting'), ('mathematics', 'Mathematics and problem solving'), ('languages', 'Foreign languages and linguistics'), ('science', 'Natural sciences and physics'), ('business', 'Business and entrepreneurship'), ('cooking', 'Cooking and culinary arts'), ('photography', 'Photography and visual media'), ('fitness', 'Fitness and exercise science'), ('philosophy', 'Philosophy and critical thinking'), ('history', 'World history and civilization'), ('psychology', 'Psychology and human behavior'), ('design', 'Graphic design and UI/UX'), ('marketing', 'Digital marketing and social media')], max_length=50),
        ),
    ]
